### ISSUE TITLE
Update state web template MVC to the latest 6.0.8 version

### ISSUE THREAD

**Issue by kkoryaka** [Office-of-Digital-Services/California-State-Web-Template-MVC#2]
Update state web template MVC to the latest 6.0.8 version

**Comment by kkoryaka** [comment]
@carterm this is now assigned to you. also please check that vulnerability alert.

**Comment by yesenia-gtz** [comment]
**To be completed by:**
[v6 Production release](https://github.com/Office-of-Digital-Services/California-State-Web-Template/milestone/3)
 Due by December 16, 2022 
Final release of State Web Template.

**Comment by yesenia-gtz** [comment]
**Beta feedback:**
In general, the code needs to be cleaned up/fine tuned.

For MVC: Just need a minimized version of the state template, not all the bells and whistles. In the applications we develop, we don't need most of the components. Focus on what applications would use. Maybe do a focus group for the MVC template.

**Comment by carterm** [comment]
.Net Core and MVC versions will be combined here...

https://github.com/Office-of-Digital-Services/California-State-Web-Template-NET-Core-MVC

**Comment by extinah** [comment]
Looks good to me! Closing. :)
